name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: SetUp Decker Compose
      run: docker compose up -d
    - name: Run Tests
      run: docker exec todo_backend sh -c "flake && pytest ."
