name: Django project Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test

    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: saeed
      POSTGRES_USER: saeed
      POSTGRES_PASSWORD: saeed

    steps:
    - uses: actions/checkout@v4
    - name: SetUp Decker Compose
      run: docker compose -f docker-compose-stage.yml up -d --build
    - name: Run Tests
      run: docker exec todo_backend sh -c "pytest ."

  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    name: Deploy
    need: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Connect and Excute commands
    - uses: appleboy/ssh-action@master
      with: 
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: 
          cd ${{secrets.PROJECT_PATH}}
          docker compose -f docker-compose-stage.yml stop
          git pull
          docker compose -f docker-compose-stage.yml restart